AllCops:
  Exclude:
    - ./bundle/**/*
    - bin/*
    - db/schema.rb
    - db/migrate/**/*
    - config/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%i': '()'

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Metrics/MethodLength:
  Max: 20
